initial commit to simplify demo app
aptible/deploy-demo-app pull request #28
Opened 2022-05-13 01:08 UTC by madhuravius

- [x] used setup.cfg
- [x] docker-compose for local setup
- [ ] use `.aptible` directory and test deployment instructions
- [ ] add .github dir with workflow examples

2022-05-13 22:16 UTC, madhuravius commented on docker-compose.yaml
> +version: "3.3"
should just be 3 👍

2022-05-13 22:17 UTC, madhuravius commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
ill do it, and honestly might just add hadolint to the linter to this (which may have detected that but will definitely grumble about unpinned versions)

2022-05-13 22:21 UTC, madhuravius commented on Dockerfile
> +RUN pip install -e .[dev]
i referenced using `install_requires` instead of `dev` (which only included some minor deps) for now

unless you meant using volume mounts and pip installing then

2022-05-13 22:39 UTC, madhuravius commented on .travis.yml
> +            --docker-image "$APTIBLE_DOCKER_IMG" \
[reading this](https://github.com/aptible/aptible-cli/blob/5b9feab12952289d7d044ceef083fac76fdc4529/lib/aptible/cli/subcommands/deploy.rb#L55), looks like it applies to the docker image options. the app/env still have to be specified unless i'm misreading, right?  so it'd probably look like this:

```sh
aptible deploy \
            --environment "$APTIBLE_ENVIRONMENT" \
            --app "$APTIBLE_APP" \
```

2022-05-16 12:46 UTC, aguilinger commented on .travis.yml
> +            --docker-image "$APTIBLE_DOCKER_IMG" \
correct

2022-05-17 23:36 UTC, madhuravius commented on Dockerfile
> -# WARNING: the following is applicable only for Direct Docker Image Deployment
revert this change and leave the Procfile in the root and move it over after

2022-05-17 23:48 UTC, madhuravius commented on .python-version
> +3.10.3
probably can remove this file, we don't want to include stuff that's not required

2022-05-17 23:49 UTC, madhuravius commented on docker-compose.yaml
> +version: "3"
remove this file for now as it is not fully necessary

2022-05-18 00:16 UTC, madhuravius commented
also may want to break out setup.cfg/pyproject.toml into separate commits (in chunked update/cleanup PR so it is easier to follow for someone tracking up commits)

2022-05-18 04:19 UTC, UserNotFound requested changes
Overall, I am concerned with the amount of content added here that does not pertain directly to deploying to Aptible. We have people that ask "Which back-end languages and their versions do you support? (e.g. php, .Net, etc)" at this point in their experience, so I would be wary of anything:

* not commented on in-line and/or linked to Aptible documentation
* any code/configuration/settings not required to deploy to Aptible.

Perhaps some of the things here might better be included in a guide covering best practices for harmonious local development?

2022-05-18 04:19 UTC, UserNotFound commented on Dockerfile
> +RUN pip install -e .[install_requires]
If this is the preferred way to manage packages, perhaps we should suggest to CRE that we update [our quickstart guide](https://deploy-docs.aptible.com/docs/python-quickstart) to this method.

2022-05-18 04:19 UTC, UserNotFound commented on Dockerfile
> +# second row needed for common libraries used (ex: gcc)
We should leave comments here explaining why we ordered the Dockerfile as we did.  There were two(?) other comments also removed that were intentionally added to help understand best practices for layer caching.

2022-05-18 04:19 UTC, UserNotFound commented on Makefile
> +SHELL := /bin/bash
Please lead with a comment about the intention of this Makefile and maybe even the targets. A Makefile is not required to build or Deploy to Aptible.

2022-05-18 04:19 UTC, UserNotFound commented on docker-compose.yaml
> +version: "3"
Please lead with a comment about the intention of the compose file, since a compose file is neither required nor support on Aptible.

2022-05-18 04:19 UTC, UserNotFound commented on scripts/server-entrypoint.sh
> +#! /usr/bin/env bash
Comment on the purpose of this file? It is not required (nor does it appear to be used) when deploying to Aptible

2022-05-18 04:19 UTC, UserNotFound commented on .aptible/Procfile
> +background: exec python -m worker
Update: we found out it does not! We can still pull the Procfile out of the image after we built it ourselves. TIL!

2022-05-18 12:29 UTC, madhuravius commented on Dockerfile
> +FROM ghcr.io/multi-py/python-gunicorn:py3.10-slim-latest
no need since we do not support local development for this repository. just gonna use the default python:3

2022-05-18 12:51 UTC, madhuravius commented on .travis.yml
> +            --docker-image "$APTIBLE_DOCKER_IMG" \
using this in subsequent docker image deploy examples

2022-05-18 12:51 UTC, madhuravius commented on Dockerfile
> +# second row needed for common libraries used (ex: gcc)
this was a mistake on my part, testing dependencies and updating again (i had some extra ones in here)

2022-05-18 13:05 UTC, madhuravius commented on Dockerfile
> +RUN pip install -e .[install_requires]
Yeah I planned on updating these with CRE as we are referencing things that are past EOL: https://devguide.python.org/#status-of-python-branches ~ 4 months

ruby - https://deploy-docs.aptible.com/docs/ruby-quickstart#add-a-dockerfile
eol - https://www.ruby-lang.org/en/downloads/branches/ 2+ years

nodejs - https://deploy-docs.aptible.com/docs/node-js-quickstart#add-a-dockerfile
eol - https://access.redhat.com/announcements/4636741 2 + years

gonna take a bit to update those and possible respective repos but i'll check on each one and generate a backlog for it

2022-05-18 13:15 UTC, madhuravius commented
> 

I removed all references to new files that are unnecessary for now, I kept a branch locally and will do what the team desires after discussion. It may live in a separate repository as a consequence

2022-05-19 05:27 UTC, UserNotFound approved these changes
These updates look great. I hadn't considered before how odd the Makefile, latest.mk, and config.mk looked until they were gone! Everything seems much clearer now.

2022-06-10 20:13 UTC, merged